### ISSUE TITLE
论文原结果复现

### ISSUE THREAD

**Issue by zq0x7a0x71** [fooSynaptic/infersent_edition#1]
你好，请问你复现过原 github (https://github.com/facebookresearch/InferSent)  上提到的训练结果吗？

原作者说 "You should obtain a dev accuracy of 85 and a test accuracy of 84.5 with the default setting." 但我最后只跑出了大概 81 左右的结果。请问里边有什么问题吗？

如果方便的话可以加个联系方式交流一下吗？

谢谢！

**Comment by fooSynaptic** [comment]
81应该够了，这个rep之所以这么多star也是因为复现简单，我自己在中文语料上面做训练好像高于85，毕竟一年之前的trial了。

**Comment by zq0x7a0x71** [comment]
@fooSynaptic 好吧，谢谢。这么出名的论文结果竟然不能复现，我本以为是自己哪里搞错了。
